robot_dynamixel_pan_joint:
  # hardware ID of the actuator
  ID: 1
  # velocity, position
  control_mode: position
  spin: 1
robot_dynamixel_tilt_joint:
  # hardware ID of the actuator
  ID: 2
  # velocity, position
  control_mode: position
  spin: 1  