joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
dynamixel_pan_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)dynamixel_pan_joint
dynamixel_tilt_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)dynamixel_tilt_joint